apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::565124524335:role/eksctl-eksctl-demo-nodegroup-ng-0-NodeInstanceRole-124GDZFNJ2SR7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::565124524335:role/UdacityFlaskDeployCBKubectlRole
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-24T22:21:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1334"
  uid: 7b801cbf-8a82-445a-9eb3-2c947d072bca
